### PR TITLE
Michael's Opinions!

### PR DESCRIPTION
**Pull request by illegalprime**
Basic redesign, feel free to take and leave any decisions I made:

1. Add margins to all pages (only on desktop).
2. Brighten the background.
3. Increase font size.
4. Polish menu, footer, and misc spacing issues.
5. Do not change animation when scrolling.
6. Consistent dark theme.
7. Other opinionated "improvements"
8. Still works on mobile.

### CODE REVIEW

**Comment by mjkaufer** [comment]
This is actually way hotter, ty for your service

Some things I noticed

* When resizing main page to have a narrow width, there's no margin on the 'HackGT' logo, and it gets chopped off by the navbar – see [here](https://i.imgur.com/rwSnVXp.png)
* More #smallPagesThings, events page chops off the year nav on a smaller width – see [here](https://i.imgur.com/JSQEsjh.png) and [here](https://i.imgur.com/HMJ043A.png)
    * Consider just hiding it entirely on smaller screens, bc it's hard to fit into a mobile view with the smaller margins
* There's also this weird black bar above the footer – see [here](https://i.imgur.com/6Tt9yIB.png)

Other than that, looks dope

**Comment by kexin-zhang** [comment]
I like the idea of more spacing/margins and larger fonts! There were a couple of small things on mobile that look a little off.
 
- On mobile, you have to scroll down on the home page to see the down arrow. It should probably just be at the bottom the screen without scrolling down. - [see here](https://imgur.com/a/3RFWY)
- Also, I'm not sure if I'm a huge fan of the justified text spacing. There are some big gaps between words. - [example](https://imgur.com/a/jnoVd)

I'll take a closer look tomorrow but I'm a fan of a lot of the changes!

**Comment by petschekr** [comment]
One more thing: the Made with ❤️ by the HackGTeam is awkwardly positioned at the bottom. Not entirely to the right and not entirely to the center.

**Review by mjkaufer — APPROVED** [review]
<3

**Pull request merged**
