### PR TITLE
Lots changes

### PR DESCRIPTION
**Pull request by jacobj10**
Kind of out of the scope of blog-dev but oh well. Try running the website and let me know what you think. It appears to be almost finished (or at least almost ready to be deployed)

### CODE REVIEW

**Review by bunsenmcdubbs — APPROVED** [review]
You would not believe the ruse cruise that I just underwent to build this site (still having issues with ImageMagick on my Mac) - hint: it involves learning Docker and building an image just so I could `jekyll build` this site.

Looks good. More content needed from Communications etc. but that's not as much of your concern.

We should be looking to get this deployed in a staging/dev environment so other people can see what the site looks like (and so Communications will know where/what the content they need to make). cc @illegalprime @ehsanmasdar

**Comment by illegalprime** [comment]
@BunsenMcDubbs agree, we'll make a ghpages for it first.

**Review by illegalprime — APPROVED** [review]
Looks good, and I can run it on my machine. We should get some standard image for it soon (since it requires linux stuff).

**Comment by bunsenmcdubbs** [comment]
@jacobj10 merge when you are ready 👍

**Pull request merged**
