### PR TITLE
Quick fixes

### PR DESCRIPTION
**Pull request by kexin-zhang**
First round of small adjustments:
- fixed broken links under pictures on home page
- fixed broken 'attend' link on home page
- fixed capitalization on code page
- made the 'catch us on social media' on contact page the same font as the rest of the text
- added timeline-glyph.svg which was missing earlier
- made the about page team description the same font size as the paragraphs on top 
- added more spacing between the blurbs on the front page
- add word breaking to exec member descriptions on event page to avoid overlap on smaller screens

### CODE REVIEW

**Review by mjkaufer — CHANGES_REQUESTED** [review]
Everything looks dope, one minor exception is the exec listing. Peep https://i.imgur.com/0rO0r2t.png

One potential fix could be disabling text wrap until you hit the breakpoint that stacks the exec members into columns (I think it's like 720px or something). Another thought is to just have the execs break into custom columns earlier – maybe make some custom grid logic for that. I can try and tackle this tomorrow tho.

**Review by jacobj10 — APPROVED** [review]
lgtm

**Review by ehsanmasdar — CHANGES_REQUESTED** [review]
Mobile needs some work

**Comment by kexin-zhang** [comment]
@ehsanmasdar @mjkaufer I think we've covered most of what we've detailed in the issues. Let's double check that and try to get this all finished/deployed on hack.gt sometime today.

**Review by mjkaufer — APPROVED** [review]

**Review by ehsanmasdar — APPROVED** [review]

**Pull request merged**
